name: Fetch Informations

permissions:
  contents: write

on:
  schedule:
    - cron: '0 0 * * *' # 每天 UTC 0 点运行
  workflow_dispatch:

jobs:
  fetch-and-save:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get timestamp
        id: get-timestamp
        run: echo "timestamp=$(date -u +'%Y%m%dT%H%M%SZ')" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt install cloudflare-warp
          warp-cli registration new
          warp-cli connect
          curl -s https://www.cloudflare.com/cdn-cgi/trace/
      
      - name: Fetch informations
        run: |
          mkdir -p briefings
          python main.py
      - name: Commit and push new info file
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add briefings/*.json
          git commit -m "Add info for ${{ steps.get-timestamp.outputs.timestamp }} UTC" || echo "Nothing to commit"
          git push
